version: '3'

services:
  spark:
    image: docker.io/bitnami/spark:3.5
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=yes
      - SPARK_RPC_AUTHENTICATION_SECRET=${SPARK_RPC_AUTHENTICATION_SECRET}
      - SPARK_RPC_ENCRYPTION_ENABLED=yes
#      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=yes
      - SPARK_SSL_ENABLED=no
#      - SPARK_SSL_KEY_PASSWORD=${SPARK_SSL_KEY_PASSWORD}
#      - SPARK_SSL_KEYSTORE_PASSWORD=${SPARK_SSL_KEYSTORE_PASSWORD}
#      - SPARK_SSL_TRUSTSTORE_PASSWORD=${SPARK_SSL_TRUSTSTORE_PASSWORD}
#      - SPARK_SSL_KEYSTORE_FILE=${SPARK_SSL_KEYSTORE_FILE}
#      - SPARK_SSL_TRUSTSTORE_FILE=${SPARK_SSL_TRUSTSTORE_FILE}
#      - SPARK_SSL_NEED_CLIENT_AUTH=yes
      - SPARK_SSL_PROTOCOL=TLSv1.2
      - SPARK_MASTER_WEBUI_PORT=${SPARK_MASTER_WEBUI_PORT}
      - SPARK_MASTER_PORT=${SPARK_MASTER_PORT}
#    volumes:
#      - ./certs:/opt/bitnami/spark/certs
    ports:
      - "${SPARK_MASTER_PORT}:${SPARK_MASTER_PORT}"
      - "${SPARK_MASTER_WEBUI_PORT}:${SPARK_MASTER_WEBUI_PORT}"

  spark-worker:
    image: docker.io/bitnami/spark:3.5
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://${SPARK_MASTER_URL}:${SPARK_MASTER_PORT}
      - SPARK_WORKER_MEMORY=${SPARK_WORKER_MEMORY}
      - SPARK_WORKER_CORES=${SPARK_WORKER_CORES}
      - SPARK_RPC_AUTHENTICATION_ENABLED=yes
      - SPARK_RPC_AUTHENTICATION_SECRET=${SPARK_RPC_AUTHENTICATION_SECRET}
      - SPARK_RPC_ENCRYPTION_ENABLED=yes
#      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=yes
      - SPARK_SSL_ENABLED=no
#      - SPARK_SSL_KEY_PASSWORD=${SPARK_SSL_KEY_PASSWORD}
#      - SPARK_SSL_KEYSTORE_PASSWORD=${SPARK_SSL_KEYSTORE_PASSWORD}
#      - SPARK_SSL_TRUSTSTORE_PASSWORD=${SPARK_SSL_TRUSTSTORE_PASSWORD}
#      - SPARK_SSL_KEYSTORE_FILE=${SPARK_SSL_KEYSTORE_FILE}
#      - SPARK_SSL_TRUSTSTORE_FILE=${SPARK_SSL_TRUSTSTORE_FILE}
#      - SPARK_SSL_NEED_CLIENT_AUTH=yes
      - SPARK_SSL_PROTOCOL=TLSv1.2
#    volumes:
#      - ./certs2:/opt/bitnami/spark/certs
